feat: refatoracao metodo comprar produto
jusylopes/koru-mobile-projeto-3 pull request #36
Opened 2024-04-12 18:30 UTC by WillianSeidel

##  📝 Changelog

- Refatoração de método comprar produto;

2024-04-12 19:02 UTC, nubiabarcellar approved these changes
Perfeito, aprovado!

2024-04-12 19:04 UTC, evelyn-vanielly approved these changes
Certo. Aprovado!

2024-04-12 23:17 UTC, viniciusjsouza approved these changes
aprovado

2024-04-13 02:33 UTC, jusylopes requested changes
Oi, Will... antes de mergear precisa fazer essa pequena alteração. Ok?!

2024-04-13 02:33 UTC, jusylopes commented on classes/cliente.dart
>          ? _realizarCompra(produto, revendedor)
Will, a lógica do try catch deveria estar dentro do método privado _realizarCompra. Ok?!

2024-04-14 18:05 UTC, WillianSeidel commented on classes/cliente.dart
>          ? _realizarCompra(produto, revendedor)
Beleza, alterado.

2024-04-14 18:11 UTC, jusylopes approved these changes
Perfeito, aprovado.

2024-04-14 18:11 UTC, merged