fix: criar metodo ordenar brindes
jusylopes/koru-mobile-projeto-3 pull request #52
Opened 2024-04-16 22:40 UTC by evelyn-vanielly

# # 📝 Changelog
- Correção do método ordenar brindes da classe "brindes" para a classe "cliente";

2024-04-17 01:08 UTC, WillianSeidel approved these changes
Perfeito!!!

2024-04-17 11:26 UTC, jusylopes requested changes

2024-04-17 11:26 UTC, jusylopes commented on classes/cliente.dart
> +    brindesOrdenados.sort((a, b) {
Oie Evy, aqui é mais apropriado usarmos a lista de brindes de dentro da classe. No caso task do Alê ainda não concluída.

2024-04-18 01:29 UTC, jusylopes approved these changes

2024-04-18 01:29 UTC, merged